## Import libraries

In [1]:
import sys
sys.path.append('/Users/zoltan/Documents/Rivabar/rivabar')

In [ ]:
## Import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import rasterio
import pyproj
from rasterio.crs import CRS
import cartopy.crs as ccrs
from matplotlib_scalebar.scalebar import ScaleBar
import matplotlib.ticker as mticker
from pystac_client import Client
import rivabar as rb

%matplotlib qt
plt.rcParams['svg.fonttype'] = 'none'

In [3]:
cd ..

/Users/zoltan/Documents/Rivabar/rivabar

In [14]:
# Remove all rivabar modules from cache
modules_to_remove = [key for key in sys.modules.keys() if key.startswith('rivabar')]
for module in modules_to_remove:
    del sys.modules[module]

# Fresh import
import rivabar as rb

## Branco River, Brazil

You can find the links to the Landsat bands that are needed by running this cell. Clicking the links will download the raster files.

In [5]:
catalog = Client.open("https://landsatlook.usgs.gov/stac-server")
scene_id = "LC82320602014050LGN02"
search = catalog.search(
    collections=["landsat-c2l2-sr"],
    query={"landsat:scene_id": {"eq": scene_id}},
    limit=1
)
item = next(search.items())
for band in ['red', 'green', 'blue', 'swir16']:
    print(item.assets[band].href)

https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/232/060/LC08_L2SP_232060_20140219_20200911_02_T1/LC08_L2SP_232060_20140219_20200911_02_T1_SR_B4.TIF
https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/232/060/LC08_L2SP_232060_20140219_20200911_02_T1/LC08_L2SP_232060_20140219_20200911_02_T1_SR_B3.TIF
https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/232/060/LC08_L2SP_232060_20140219_20200911_02_T1/LC08_L2SP_232060_20140219_20200911_02_T1_SR_B2.TIF
https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/232/060/LC08_L2SP_232060_20140219_20200911_02_T1/LC08_L2SP_232060_20140219_20200911_02_T1_SR_B6.TIF

### Create water index image and pick start- and end points for channel belt

In [9]:
# Create river without start/end points initially
river = rb.River(
    fname='LC08_L2SP_232060_20140219_20200911_02_T1_SR',
    dirname='data/Branco/',
    file_type='multiple_tifs'
)

# Create and visualize MNDWI first
mndwi = river.create_mndwi(mndwi_threshold=0.01)
river.plot_mndwi();

Creating MNDWI for: LC08_L2SP_232060_20140219_20200911_02_T1_SR

100%|██████████| 4/4 [00:00<00:00,  4.96it/s]

✓ MNDWI created: (7731, 7581)
  - Water pixels: 213,071.0
  - Total pixels: 58,608,711
  - Water percentage: 0.4%

In [10]:
# Pick start and end points
river.get_start_end_points_interactive()

Click two points: first for START, second for END
Start point: (678565.8, 103090.2)
End point: (627360.4, -96836.5)

(np.float64(678565.762987013),
 np.float64(103090.17857142855),
 np.float64(627360.4383116884),
 np.float64(-96836.4935064935))

### Extract channel centerlines and banklines

In [11]:
river.map_river_banks(
    ch_belt_smooth_factor=1e8,
    ch_belt_half_width=2000,
    remove_smaller_components=False,
    small_hole_threshold=64,
    solidity_filter=False,
    plot_D_primal=True, 
    flip_outlier_edges=True,
    check_edges=False
)

Processing river: LC08_L2SP_232060_20140219_20200911_02_T1_SR
Start point: (678565.762987013, 103090.17857142855)
End point: (627360.4383116884, -96836.4935064935)
Phase 1: Initial setup and skeletonization

100%|██████████| 4/4 [00:00<00:00,  4.91it/s]

running skeletonization
Phase 2: Finding main path with fallbacks
Phase 3: Processing graph and extending edges

100%|██████████| 200/200 [00:01<00:00, 191.74it/s]

Phase 4: Extracting and smoothing main path
Phase 5: Polygonizing centerline network

100%|██████████| 423/423 [00:00<00:00, 23132.46it/s]

Phase 6: Creating channel belt and boundaries
Phase 7: Create UTM geodataframe

100%|██████████| 63/63 [00:00<00:00, 5300.41it/s]

Phase 8: Create primal graph

65it [00:00, 400.60it/s]

start and end nodes in G_primal:
42 1
Phase 9: Create rook graph

100%|██████████| 7339/7339 [00:00<00:00, 27834.77it/s]
100%|██████████| 7112/7112 [00:00<00:00, 30664.55it/s]
100%|██████████| 63/63 [00:06<00:00,  9.41it/s]

Phase 10: Set half channel widths

100%|██████████| 65/65 [00:19<00:00,  3.38it/s]

Phase 11: Create directed graph

100%|██████████| 189/189 [00:01<00:00, 131.20it/s]

Phase 12: Get bank coordinates for main channel

100%|██████████| 6770/6770 [00:00<00:00, 29248.47it/s]
100%|██████████| 6770/6770 [00:00<00:00, 22133.01it/s]
100%|██████████| 63/63 [00:00<00:00, 4737.20it/s]
100%|██████████| 189/189 [00:00<00:00, 1977.86it/s]

✓ Successfully processed LC08_L2SP_232060_20140219_20200911_02_T1_SR
  - Directed graph: 126 nodes, 189 edges
  - Rook graph: 65 polygons
  - Primal graph: 126 nodes

True

In [15]:
river_branco = river
stats = rb.collect_river_stats(river_branco)
print(stats)

{'n_nodes_rook': 65, 'n_edges_rook': 157, 'n_nodes_primal': 126, 'n_edges_primal': 189, 'degree_mean': np.float64(3.2857142857142856), 'degree_median': np.float64(3.0), 'degree_std': np.float64(1.3023613648740324), 'degree_node0': 56, 'degree_node1': 51, 'island_area_mean': np.float64(1859712.0267244426), 'island_area_median': np.float64(312987.80955032655), 'island_area_std': np.float64(3624761.787752536), 'island_length_mean': np.float64(5408.06644859771), 'island_length_median': np.float64(2625.198791309816), 'island_length_std': np.float64(6442.781899097129), 'n_islands': 63, 'width_mean': np.float64(532.9509294401042), 'width_median': np.float64(510.878553586683), 'width_std': np.float64(204.68016788850093), 'centerline_length': np.float64(234504.27042941438), 'sinuosity': np.float64(1.237851324023646)}

In [16]:
from rivabar.polygon_processing import create_channel_nw_polygon, plot_polygon

ch_poly = create_channel_nw_polygon(river._G_rook, buffer=10, dataset=river._dataset)

fig, ax = plt.subplots(figsize=(14, 10))
plot_polygon(ax, ch_poly, facecolor='royalblue', edgecolor='k', linewidth=0.3, alpha=0.7)
ax.set_aspect('equal')

In [17]:
island_areas = []
channel_areas = []
total_areas = []
degrees = []
lengths = []
for node in river._G_rook:
    poly1 = river._G_rook.nodes()[node]['bank_polygon']
    poly2 = river._G_rook.nodes()[node]['cl_polygon']
    if poly1.area > 0 and poly2.area > poly1.area:
        island_areas.append(poly1.area)
        channel_areas.append(poly2.area - poly1.area)
        total_areas.append(poly2.area)
        degrees.append(river._G_rook.degree(node))
        lengths.append(poly1.length)
        
island_areas_sorted = np.sort(island_areas)
island_areas_sorted = island_areas_sorted[:-2]
exceedance = 1.-np.arange(1.,len(island_areas_sorted) + 1.)/len(island_areas_sorted)

plt.figure()
plt.loglog(island_areas_sorted, exceedance)
plt.xlabel('island area (m2)')
plt.ylabel('exceedance probability');

In [18]:
plt.figure()
n, bins, patches = plt.hist(degrees, bins=np.arange(1.5, 25.6, 1))

plt.bar(np.arange(2,26), n)
plt.xticks(np.arange(2,26))
plt.xlabel('node degree')
plt.ylabel('count')
plt.title('number of neighbors in island neighborhood graph');

In [19]:
# Create water mask from River
water_mask = rb.create_water_mask_from_river(river, output_path='water_mask.tif')

# Visualize
import matplotlib.pyplot as plt
plt.figure()
plt.imshow(water_mask, cmap='Blues', extent=[river.dataset.bounds.left, river.dataset.bounds.right, river.dataset.bounds.bottom, river.dataset.bounds.top])
plt.title('Water Mask from Rivabar Mapping')
plt.colorbar(label='Water (1) / Land (0)')
plt.axis('equal');

Water mask saved to: water_mask.tif

### Plot width data for main channel

In [20]:
s, w = river.get_channel_widths()
plt.figure(figsize=(12, 4))
plt.plot(s, w)
plt.xlabel('along-channel distance (m)')
plt.ylabel('channel width (m)');

### Plot banks and centerline for main channel

In [21]:
lbx = river.main_channel_banks['left_bank'].xy[0]
lby = river.main_channel_banks['left_bank'].xy[1]
rbx = river.main_channel_banks['right_bank'].xy[0]
rby = river.main_channel_banks['right_bank'].xy[1]
plt.figure()
plt.plot(lbx, lby, 'k')
plt.plot(rbx, rby, 'k')
plt.axis('equal');

### Save results to shapefiles

In [24]:
rb.write_shapefiles_and_graphs(river._G_rook, river._D_primal, 
                               river._dataset, river.dirname, 'Branco')

### Save results to pickle file

In [25]:
river.save_results('Branco_results.pkl')

Saved results to Branco_results.pkl

In [26]:
from rivabar.river import River
river = River.load_results('Branco_results.pkl')

Loaded results from Branco_results.pkl

## Mamore River, Bolivia


Data download links:

In [27]:
catalog = Client.open("https://landsatlook.usgs.gov/stac-server")
scene_id = "LC82320712016168LGN01"
search = catalog.search(
    collections=["landsat-c2l2-sr"],
    query={"landsat:scene_id": {"eq": scene_id}},
    limit=1
)
item = next(search.items())
for band in ['red', 'green', 'blue', 'swir16']:
    print(item.assets[band].href)

https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2016/232/071/LC08_L2SP_232071_20160616_20200906_02_T1/LC08_L2SP_232071_20160616_20200906_02_T1_SR_B4.TIF
https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2016/232/071/LC08_L2SP_232071_20160616_20200906_02_T1/LC08_L2SP_232071_20160616_20200906_02_T1_SR_B3.TIF
https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2016/232/071/LC08_L2SP_232071_20160616_20200906_02_T1/LC08_L2SP_232071_20160616_20200906_02_T1_SR_B2.TIF
https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2016/232/071/LC08_L2SP_232071_20160616_20200906_02_T1/LC08_L2SP_232071_20160616_20200906_02_T1_SR_B6.TIF

In [28]:
# in this case, the start and end points are known and are provided as arguments
river = rb.River(
    fname='LC08_L2SP_232071_20160616_20200906_02_T1_SR',
    dirname='data/Mamore/',
    start_x = 303810,
    start_y = -1851620,
    end_x = 285603,
    end_y = -1666131,
    file_type='multiple_tifs'
)

In [29]:
river.map_river_banks(
    ch_belt_smooth_factor=1e8,
    ch_belt_half_width=2000,
    remove_smaller_components=False,
    small_hole_threshold=64,
    solidity_filter=False,
    plot_D_primal=True, 
    flip_outlier_edges=False,
    check_edges=False
)

Processing river: LC08_L2SP_232071_20160616_20200906_02_T1_SR
Start point: (303810, -1851620)
End point: (285603, -1666131)
Phase 1: Initial setup and skeletonization

100%|██████████| 4/4 [00:00<00:00,  4.32it/s]

running skeletonization
Phase 2: Finding main path with fallbacks
no path between start_ind and end_ind
Phase 3: Processing graph and extending edges

100%|██████████| 66/66 [00:00<00:00, 544.51it/s]

Phase 4: Extracting and smoothing main path
Phase 5: Polygonizing centerline network

100%|██████████| 77/77 [00:00<00:00, 23447.18it/s]

Phase 6: Creating channel belt and boundaries
Phase 7: Create UTM geodataframe

100%|██████████| 12/12 [00:00<00:00, 5321.60it/s]

Phase 8: Create primal graph

14it [00:00, 119.89it/s]

start and end nodes in G_primal:
2 1
Phase 9: Create rook graph

100%|██████████| 14245/14245 [00:00<00:00, 39335.42it/s]
100%|██████████| 13552/13552 [00:00<00:00, 40332.51it/s]
100%|██████████| 12/12 [00:01<00:00,  9.51it/s]

Phase 10: Set half channel widths

100%|██████████| 14/14 [00:09<00:00,  1.42it/s]

Phase 11: Create directed graph

100%|██████████| 37/37 [00:00<00:00, 64.40it/s]

Phase 12: Get bank coordinates for main channel

100%|██████████| 13399/13399 [00:00<00:00, 38610.95it/s]
100%|██████████| 13399/13399 [00:00<00:00, 38269.18it/s]
100%|██████████| 12/12 [00:00<00:00, 3960.32it/s]
100%|██████████| 37/37 [00:00<00:00, 546.65it/s]

✓ Successfully processed LC08_L2SP_232071_20160616_20200906_02_T1_SR
  - Directed graph: 26 nodes, 37 edges
  - Rook graph: 14 polygons
  - Primal graph: 26 nodes

True

In [30]:
river_mamore = river
stats = rb.collect_river_stats(river_mamore)
print(stats)

{'n_nodes_rook': 14, 'n_edges_rook': 25, 'n_nodes_primal': 26, 'n_edges_primal': 37, 'degree_mean': np.float64(2.0), 'degree_median': np.float64(2.0), 'degree_std': np.float64(0.0), 'degree_node0': 13, 'degree_node1': 13, 'island_area_mean': np.float64(313470.9971370967), 'island_area_median': np.float64(121250.16923306239), 'island_area_std': np.float64(350668.31484479207), 'island_length_mean': np.float64(2284.816038010536), 'island_length_median': np.float64(1859.244501662175), 'island_length_std': np.float64(1148.9732098152665), 'n_islands': 12, 'width_mean': np.float64(257.583447968636), 'width_median': np.float64(243.69316876852986), 'width_std': np.float64(77.36119085478741), 'centerline_length': np.float64(455161.09603307175), 'sinuosity': np.float64(2.5362687623390676)}

### Plot width data for main channel

In [31]:
s, w = river.get_channel_widths()
plt.figure(figsize=(12, 4))
plt.plot(s, w) 
plt.xlabel('along-channel distance (m)')
plt.ylabel('channel width (m)');

### Plot meander wavelength and channel width data

In [32]:
fig, ax = river.plot_overview()
df, curv, s, loc_zero_curv, xsmooth, ysmooth = river.analyze_wavelength_and_width(ax=ax, delta_s=5, smoothing_factor=0.5*1e7, min_sinuosity=1.3, dx=30)
df.head()

100%|██████████| 12/12 [00:00<00:00, 1948.65it/s]
100%|██████████| 37/37 [00:00<00:00, 2501.64it/s]

,wavelengths (m),sinuosities,mean widths (m),std. dev. of widths (m),along-channel distance (km)
0,2583.395531,2.033661,146.498650,29.657718,8.301246
1,5458.838402,1.727062,205.756678,44.742822,16.953641
2,2909.161183,4.201614,204.577181,32.829278,25.625496
3,3496.961110,1.846768,197.688200,49.302042,30.287027
4,3392.761745,1.980359,167.964591,48.274098,41.374331

### Map a longer river segment

In [33]:
river = rb.River(
    fname='L8_mndwi_Mamore_2015_UTM.tif',
    dirname='/Users/zoltan/Documents/Channels/Fluvial/Mamore/',
    start_x = 303559.07,
    start_y = 8148946.7,
    end_x = 271009.56,
    end_y = 8549337.76,
    file_type='water_index'
)

river.map_river_banks(
    ch_belt_smooth_factor=1e8,
    ch_belt_half_width=2000,
    remove_smaller_components=False,
    small_hole_threshold=64,
    solidity_filter=False,
    plot_D_primal=True,
    flip_outlier_edges=False,
    check_edges=False
)

Processing river: L8_mndwi_Mamore_2015_UTM.tif
Start point: (303559.07, 8148946.7)
End point: (271009.56, 8549337.76)
Phase 1: Initial setup and skeletonization
running skeletonization
Phase 2: Finding main path with fallbacks
Phase 3: Processing graph and extending edges

100%|██████████| 230/230 [00:00<00:00, 315.68it/s]

Phase 4: Extracting and smoothing main path
Phase 5: Polygonizing centerline network

100%|██████████| 257/257 [00:00<00:00, 27027.46it/s]

Phase 6: Creating channel belt and boundaries
Phase 7: Create UTM geodataframe

100%|██████████| 9/9 [00:00<00:00, 5137.28it/s]

Phase 8: Create primal graph

11it [00:00, 48.25it/s]

start and end nodes in G_primal:
12 1
Phase 9: Create rook graph

100%|██████████| 27615/27615 [00:00<00:00, 35199.28it/s]
100%|██████████| 27638/27638 [00:00<00:00, 35539.50it/s]
100%|██████████| 9/9 [00:00<00:00, 12.82it/s]

Phase 10: Set half channel widths

100%|██████████| 11/11 [00:13<00:00,  1.19s/it]

Phase 11: Create directed graph

100%|██████████| 28/28 [00:00<00:00, 30.90it/s]

Phase 12: Get bank coordinates for main channel

100%|██████████| 27433/27433 [00:00<00:00, 35450.30it/s]
100%|██████████| 27433/27433 [00:00<00:00, 35140.60it/s]
100%|██████████| 9/9 [00:00<00:00, 3668.84it/s]
100%|██████████| 28/28 [00:00<00:00, 240.02it/s]

✓ Successfully processed L8_mndwi_Mamore_2015_UTM.tif
  - Directed graph: 20 nodes, 28 edges
  - Rook graph: 11 polygons
  - Primal graph: 20 nodes

True

In [34]:
river.summary()

=== River Summary: L8_mndwi_Mamore_2015_UTM.tif ===
Processed: True
Successful: True
Start point: (303559.1, 8148946.7)
End point: (271009.6, 8549337.8)
Directed graph: 20 nodes, 28 edges
Rook graph: 11 polygons
Primal graph: 20 nodes
MNDWI shape: (13843, 2926)
Main path: 18 edges
Channel width: 346.7 ± 124.7 m
Channel length: 929662.2 m
================================================

## Brahmaputra River, India / Bangladesh


Data download links:

In [35]:
catalog = Client.open("https://landsatlook.usgs.gov/stac-server")
scene_id = "LC81380422019014LGN00"
search = catalog.search(
    collections=["landsat-c2l2-sr"],
    query={"landsat:scene_id": {"eq": scene_id}},
    limit=1
)
item = next(search.items())
for band in ['red', 'green', 'blue', 'swir16']:
    print(item.assets[band].href)

https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2019/138/042/LC08_L2SP_138042_20190114_20200830_02_T1/LC08_L2SP_138042_20190114_20200830_02_T1_SR_B4.TIF
https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2019/138/042/LC08_L2SP_138042_20190114_20200830_02_T1/LC08_L2SP_138042_20190114_20200830_02_T1_SR_B3.TIF
https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2019/138/042/LC08_L2SP_138042_20190114_20200830_02_T1/LC08_L2SP_138042_20190114_20200830_02_T1_SR_B2.TIF
https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2019/138/042/LC08_L2SP_138042_20190114_20200830_02_T1/LC08_L2SP_138042_20190114_20200830_02_T1_SR_B6.TIF

In [36]:
river = rb.River(
    fname='LC08_L2SP_138042_20190114_20200830_02_T1_SR',
    dirname='data/Brahmaputra/',
    start_x = 859250.5,
    start_y = 2903119.2,
    end_x = 767358.1,
    end_y = 2776067.9,
    file_type='multiple_tifs'
)

river.map_river_banks(
    ch_belt_smooth_factor=1e8,
    ch_belt_half_width=2000,
    remove_smaller_components=True,
    small_hole_threshold=64,
    solidity_filter=False,
    plot_D_primal=True,
    flip_outlier_edges=True,
    check_edges=True
)

Processing river: LC08_L2SP_138042_20190114_20200830_02_T1_SR
Start point: (859250.5, 2903119.2)
End point: (767358.1, 2776067.9)
Phase 1: Initial setup and skeletonization

100%|██████████| 4/4 [00:00<00:00,  4.53it/s]

running skeletonization
Phase 2: Finding main path with fallbacks
Phase 3: Processing graph and extending edges

100%|██████████| 213/213 [00:05<00:00, 42.39it/s]

Phase 4: Extracting and smoothing main path
Phase 5: Polygonizing centerline network

100%|██████████| 1615/1615 [00:00<00:00, 9098.60it/s]

Phase 6: Creating channel belt and boundaries
Phase 7: Create UTM geodataframe

100%|██████████| 272/272 [00:00<00:00, 5035.56it/s]

Phase 8: Create primal graph

274it [00:00, 496.61it/s]

start and end nodes in G_primal:
5 3
Phase 9: Create rook graph

100%|██████████| 7577/7577 [00:00<00:00, 30114.55it/s]
100%|██████████| 6709/6709 [00:00<00:00, 30138.17it/s]
100%|██████████| 272/272 [00:30<00:00,  9.01it/s]

Phase 10: Set half channel widths

100%|██████████| 274/274 [01:23<00:00,  3.26it/s]

Phase 11: Create directed graph

100%|██████████| 802/802 [00:05<00:00, 135.88it/s]

Found 2 source nodes: [5, 38]
Found 3 sink nodes: [3, 163, 313]
After corrections, found 2 source nodes: [5, 51]
After corrections, found 1 sink nodes: [3]
Phase 12: Get bank coordinates for main channel

100%|██████████| 6392/6392 [00:00<00:00, 23337.51it/s]
100%|██████████| 6390/6390 [00:00<00:00, 23897.51it/s]
100%|██████████| 272/272 [00:00<00:00, 5303.20it/s]
100%|██████████| 802/802 [00:00<00:00, 1932.94it/s]

✓ Successfully processed LC08_L2SP_138042_20190114_20200830_02_T1_SR
  - Directed graph: 525 nodes, 802 edges
  - Rook graph: 274 polygons
  - Primal graph: 525 nodes

True

In [37]:
river.summary()

=== River Summary: LC08_L2SP_138042_20190114_20200830_02_T1_SR ===
Processed: True
Successful: True
Start point: (859250.5, 2903119.2)
End point: (767358.1, 2776067.9)
Directed graph: 525 nodes, 802 edges
Rook graph: 274 polygons
Primal graph: 525 nodes
MNDWI shape: (7691, 7541)
Main path: 122 edges
Channel width: 746.2 ± 282.1 m
Channel length: 221232.1 m
===============================================================

In [38]:
river_brahmaputra = river
stats = rb.collect_river_stats(river_brahmaputra)
print(stats)

{'n_nodes_rook': 274, 'n_edges_rook': 757, 'n_nodes_primal': 525, 'n_edges_primal': 802, 'degree_mean': np.float64(4.944852941176471), 'degree_median': np.float64(4.0), 'degree_std': np.float64(2.9804342324010134), 'degree_node0': 80, 'degree_node1': 89, 'island_area_mean': np.float64(3309437.247200135), 'island_area_median': np.float64(508004.4104494403), 'island_area_std': np.float64(6598460.234422196), 'island_length_mean': np.float64(6408.89927637776), 'island_length_median': np.float64(3310.47439952065), 'island_length_std': np.float64(6974.202154872535), 'n_islands': 272, 'width_mean': np.float64(746.1573783925905), 'width_median': np.float64(710.8341497358234), 'width_std': np.float64(282.1033685099875), 'centerline_length': np.float64(221232.0727199683), 'sinuosity': np.float64(1.4695393437520163)}

### Exceedance probability plot of island areas

In [39]:
island_areas = []
channel_areas = []
total_areas = []
degrees = []
lengths = []
for node in river._G_rook:
    poly1 = river._G_rook.nodes()[node]['bank_polygon']
    poly2 = river._G_rook.nodes()[node]['cl_polygon']
    if poly1.area > 0 and poly2.area > poly1.area:
        island_areas.append(poly1.area)
        channel_areas.append(poly2.area - poly1.area)
        total_areas.append(poly2.area)
        degrees.append(river._G_rook.degree(node))
        lengths.append(poly1.length)
        
island_areas_sorted = np.sort(island_areas)
island_areas_sorted = island_areas_sorted[:-2]
exceedance = 1.-np.arange(1.,len(island_areas_sorted) + 1.)/len(island_areas_sorted)

plt.figure()
plt.loglog(island_areas_sorted, exceedance)
plt.xlabel('island area (m2)')
plt.ylabel('exceedance probability');

### Histogram of node degree distribution

In [40]:
plt.figure()
n, bins, patches = plt.hist(degrees, bins=np.arange(1.5, 25.6, 1))

plt.bar(np.arange(2,26), n)
plt.xticks(np.arange(2,26))
plt.xlabel('node degree')
plt.ylabel('count')
plt.title('number of neighbors in island neighborhood graph');

## Purus River, Brazil

The water mask was generated in Google Earth Engine.

Initial output from GEE needs to be converted to UTM coordinates before running rivabar.

Link to data files: https://utexas.box.com/s/cb6wsihdoykbti1iju57rs2cfrszqmyx

In [41]:
river = rb.River(
    dirname = "data/Purus/",
    fname = "L8_mndwi_Purus_2017_UTM.tif",
    start_x = 363166.2,
    start_y = -1011937.1,
    end_x = 1254178.3,
    end_y = -528280.7,
    file_type='water_index'
)

river.map_river_banks(
    ch_belt_smooth_factor=1e8,
    ch_belt_half_width=2000,
    remove_smaller_components=True,
    small_hole_threshold=64,
    solidity_filter=False,
    plot_D_primal=True,
    flip_outlier_edges=False,
    check_edges=False
)

Processing river: L8_mndwi_Purus_2017_UTM.tif
Start point: (363166.2, -1011937.1)
End point: (1254178.3, -528280.7)
Phase 1: Initial setup and skeletonization
running skeletonization
Phase 2: Finding main path with fallbacks
Phase 3: Processing graph and extending edges

100%|██████████| 282/282 [00:02<00:00, 99.65it/s]

Phase 4: Extracting and smoothing main path
Phase 5: Polygonizing centerline network

100%|██████████| 702/702 [00:00<00:00, 15565.75it/s]

Phase 6: Creating channel belt and boundaries

Phase 7: Create UTM geodataframe

100%|██████████| 12/12 [00:00<00:00, 1246.64it/s]

Phase 8: Create primal graph

14it [00:00, 17.42it/s]

start and end nodes in G_primal:
0 11
Phase 9: Create rook graph

100%|██████████| 82583/82583 [00:02<00:00, 34835.24it/s]
100%|██████████| 86017/86017 [00:02<00:00, 34105.28it/s]
100%|██████████| 12/12 [00:11<00:00,  1.07it/s]

Phase 10: Set half channel widths

100%|██████████| 14/14 [01:27<00:00,  6.22s/it]

Phase 11: Create directed graph

100%|██████████| 37/37 [00:03<00:00, 10.88it/s]

Phase 12: Get bank coordinates for main channel

100%|██████████| 83245/83245 [00:02<00:00, 34736.35it/s]
100%|██████████| 83245/83245 [00:02<00:00, 34089.98it/s]
100%|██████████| 12/12 [00:00<00:00, 3145.53it/s]
100%|██████████| 37/37 [00:00<00:00, 87.34it/s]

✓ Successfully processed L8_mndwi_Purus_2017_UTM.tif
  - Directed graph: 26 nodes, 37 edges
  - Rook graph: 14 polygons
  - Primal graph: 26 nodes

True

In [42]:
river_purus = river
stats = rb.collect_river_stats(river_purus)
print(stats)

{'n_nodes_rook': 14, 'n_edges_rook': 28, 'n_nodes_primal': 26, 'n_edges_primal': 37, 'degree_mean': np.float64(3.0833333333333335), 'degree_median': np.float64(3.0), 'degree_std': np.float64(1.114924013354971), 'degree_node0': 8, 'degree_node1': 11, 'island_area_mean': np.float64(62665278.08233771), 'island_area_median': np.float64(8835731.062744182), 'island_area_std': np.float64(135998377.75902063), 'island_length_mean': np.float64(37376.078274938314), 'island_length_median': np.float64(16676.26821925739), 'island_length_std': np.float64(58329.81225133787), 'n_islands': 12, 'width_mean': np.float64(350.5034075862308), 'width_median': np.float64(301.22347068674145), 'width_std': np.float64(188.77002752537663), 'centerline_length': np.float64(2802522.0155137572), 'sinuosity': np.float64(2.871187920136993)}

In [43]:
river.summary()

=== River Summary: L8_mndwi_Purus_2017_UTM.tif ===
Processed: True
Successful: True
Start point: (363166.2, -1011937.1)
End point: (1254178.3, -528280.7)
Directed graph: 26 nodes, 37 edges
Rook graph: 14 polygons
Primal graph: 26 nodes
MNDWI shape: (17232, 29991)
Main path: 17 edges
Channel width: 350.5 ± 188.8 m
Channel length: 2802522.0 m
===============================================

### Plot width data for main channel

In [44]:
s, w = river.get_channel_widths()
plt.figure(figsize=(12, 4))
plt.plot(s, w) 
plt.xlabel('along-channel distance (m)')
plt.ylabel('channel width (m)');

### Plot meander wavelength and channel width data

In [45]:
fig, ax = river.plot_overview()
df, curv, s, loc_zero_curv, xsmooth, ysmooth = river.analyze_wavelength_and_width(ax=ax, delta_s=60.0, smoothing_factor=0.5*1e8, min_sinuosity=1.1, dx=30)
df.head()

100%|██████████| 12/12 [00:00<00:00, 3498.41it/s]
100%|██████████| 37/37 [00:00<00:00, 623.73it/s]

,wavelengths (m),sinuosities,mean widths (m),std. dev. of widths (m),along-channel distance (km)
0,1609.650314,1.209159,124.435145,29.363594,2.794315
1,3838.270222,3.061721,140.570330,27.274352,6.223424
2,3694.887694,1.749982,135.763613,27.507126,10.757925
3,3580.649737,1.365441,146.093856,31.568633,13.582910
4,3063.285853,1.146167,153.802742,40.679205,15.734234

In [69]:
plt.figure()
plt.hist(df['sinuosities'], bins=30)
plt.xlabel('Sinuosity')
plt.ylabel('Count')

Text(0, 0.5, 'Count')

In [70]:
print(f"Median sinuosity: {df['sinuosities'].median():.2f}")

Median sinuosity: 1.54

### Merge two files into a single TIF file (often needed when downloading files from GEE)

In [47]:
pwd

'/Users/zoltan/Documents/Rivabar/rivabar'

In [51]:
dirname = "./data/Purus/"
fname1 = 'L8_mndwi_mosaic_Purus_2019_2020-0000000000-0000000000_UTM.tif'
fname2 = 'L8_mndwi_mosaic_Purus_2019_2020-0000000000-0000032768_UTM.tif'

from rasterio.merge import merge

# Open the first raster dataset
src1 = rasterio.open(dirname+fname1) 
meta1 = src1.meta
# Open the second raster dataset
src2 = rasterio.open(dirname+fname2)
# Merge the two arrays
merged_arr, merged_transform = merge([src1, src2])
merged_arr = merged_arr[0, :, :]
# Update the metadata with the merged shape and transform
meta1.update({
    'height': merged_arr.shape[0],
    'width': merged_arr.shape[1],
    'transform': merged_transform
})
# Write the merged raster dataset to disk
with rasterio.open(dirname + 'L8_mndwi_mosaic_Purus_2019_2020_UTM.tif', 'w', **meta1) as dst:
    dst.write(merged_arr, 1)

## Putumayo

In [ ]:
# this takes ~26 minutes to run

dirname = "/Users/zoltan/Documents/Channels/Fluvial/Putumayo/"
fname = "L8_mndwi_mosaic_Putumayo_2018_2019_UTM.tif"

start_x = 316546.62
start_y = 10076194.75
end_x = 1282274.36
end_y = 9650676.18

river = rb.River(
    fname=fname,
    dirname=dirname,
    start_x=start_x,
    start_y=start_y,
    end_x=end_x,
    end_y=end_y,
    file_type='water_index',
    mndwi_threshold=0.0,
    ch_belt_smooth_factor=1e8,
    ch_belt_half_width=2000,
    remove_smaller_components=True,
    delete_pixels_polys=False,
    small_hole_threshold=100,
    solidity_filter=True
)

river.map_river_banks()
fig, ax = river.plot_overview()

Processing river: L8_mndwi_mosaic_Putumayo_2018_2019_UTM.tif
Start point: (316546.62, 10076194.75)
End point: (1282274.36, 9650676.18)
Phase 1: Initial setup and skeletonization
running skeletonization
Phase 2: Finding main path with fallbacks
no path between start_ind and end_ind
Phase 3: Processing graph and extending edges

100%|██████████| 972/972 [00:05<00:00, 180.23it/s]

Phase 4: Extracting and smoothing main path
Phase 5: Polygonizing centerline network

100%|██████████| 1651/1651 [00:00<00:00, 8464.50it/s]

Phase 6: Creating channel belt and boundaries
Phase 7: Create UTM geodataframe

100%|██████████| 321/321 [00:00<00:00, 6350.81it/s]

Phase 8: Create primal graph

323it [00:02, 128.19it/s]

start and end nodes in G_primal:
0 399
Phase 9: Create rook graph

100%|██████████| 62078/62078 [00:02<00:00, 26571.99it/s]
100%|██████████| 61066/61066 [00:02<00:00, 26791.45it/s]
100%|██████████| 321/321 [04:06<00:00,  1.30it/s]

Phase 10: Set half channel widths

100%|██████████| 323/323 [17:32<00:00,  3.26s/it]

Phase 11: Create directed graph

100%|██████████| 957/957 [01:01<00:00, 15.66it/s]

Phase 12: Get bank coordinates for main channel

100%|██████████| 58041/58041 [00:02<00:00, 26674.96it/s]
100%|██████████| 58039/58039 [00:02<00:00, 26911.62it/s]

✓ Successfully processed L8_mndwi_mosaic_Putumayo_2018_2019_UTM.tif
  - Directed graph: 632 nodes, 957 edges
  - Rook graph: 323 polygons
  - Primal graph: 632 nodes

100%|██████████| 321/321 [00:00<00:00, 5662.57it/s]
100%|██████████| 957/957 [00:00<00:00, 3117.76it/s]

In [135]:
river.save_results('Putumayo_results.pkl')

Saved results to Putumayo_results.pkl

In [57]:
stats = rb.collect_river_stats(river)
print(stats)

{'n_nodes_rook': 323, 'n_edges_rook': 722, 'n_nodes_primal': 632, 'n_edges_primal': 957, 'degree_mean': np.float64(2.6386292834890965), 'degree_median': np.float64(2.0), 'degree_std': np.float64(0.7775690949749959), 'degree_node0': 298, 'degree_node1': 299, 'island_area_mean': np.float64(2063842.0756594692), 'island_area_median': np.float64(453700.7254081225), 'island_area_std': np.float64(7120668.36851705), 'island_length_mean': np.float64(4978.458847753106), 'island_length_median': np.float64(3491.2263561832274), 'island_length_std': np.float64(6016.948263390727), 'n_islands': 321, 'width_mean': np.float64(603.6428334230401), 'width_median': np.float64(582.1684364145647), 'width_std': np.float64(240.33734936176913), 'centerline_length': np.float64(1994780.1037934453), 'sinuosity': np.float64(1.9638377888232472)}

## Mississippi River, USA

In [ ]:
# this takes ~11 minutes to run

river = rb.River(
    dirname = "/Users/zoltan/Documents/Channels/Fluvial/Mississippi/",
    fname = "L8_mndwi_Mississippi_2019_UTM_edited_2_no_delta_geo.tif",
    start_x = 845257.5,
    start_y = 4099939.1,
    end_x = 877774.5,
    end_y = 3212403.1,
    file_type='water_index'
)

river.map_river_banks(
    ch_belt_smooth_factor=1e8,
    ch_belt_half_width=2000,
    mndwi_threshold=0.5,
    remove_smaller_components=True,
    small_hole_threshold=100,
    solidity_filter=False,
    plot_D_primal=True,
    flip_outlier_edges=False,
    check_edges=False
)

Processing river: L8_mndwi_Mississippi_2019_UTM_edited_2_no_delta_geo.tif
Start point: (845257.5, 4099939.1)
End point: (877774.5, 3212403.1)
Phase 1: Initial setup and skeletonization
running skeletonization
Phase 2: Finding main path with fallbacks
Phase 3: Processing graph and extending edges

100%|██████████| 1248/1248 [00:22<00:00, 56.40it/s]

Phase 4: Extracting and smoothing main path
Phase 5: Polygonizing centerline network

100%|██████████| 2618/2618 [00:00<00:00, 5480.35it/s]

Phase 6: Creating channel belt and boundaries
Phase 7: Create UTM geodataframe

100%|██████████| 204/204 [00:00<00:00, 5189.68it/s]

Phase 8: Create primal graph

206it [00:01, 148.06it/s]

start and end nodes in G_primal:
188 129
Phase 9: Create rook graph

100%|██████████| 48587/48587 [00:02<00:00, 18333.15it/s]
100%|██████████| 45786/45786 [00:02<00:00, 17527.96it/s]
100%|██████████| 204/204 [01:31<00:00,  2.24it/s]

Phase 10: Set half channel widths

100%|██████████| 206/206 [06:23<00:00,  1.86s/it]

Phase 11: Create directed graph

100%|██████████| 611/611 [00:30<00:00, 20.29it/s]

Phase 12: Get bank coordinates for main channel

100%|██████████| 43128/43128 [00:02<00:00, 16084.68it/s]
100%|██████████| 43128/43128 [00:02<00:00, 16366.27it/s]
100%|██████████| 204/204 [00:00<00:00, 5737.42it/s]
100%|██████████| 611/611 [00:00<00:00, 1215.22it/s]

✓ Successfully processed L8_mndwi_Mississippi_2019_UTM_edited_2_no_delta_geo.tif
  - Directed graph: 407 nodes, 611 edges
  - Rook graph: 206 polygons
  - Primal graph: 407 nodes

True

In [61]:
stats = rb.collect_river_stats(river)
print(stats)

{'n_nodes_rook': 206, 'n_edges_rook': 496, 'n_nodes_primal': 407, 'n_edges_primal': 611, 'degree_mean': np.float64(3.0980392156862746), 'degree_median': np.float64(3.0), 'degree_std': np.float64(1.2248233479797188), 'degree_node0': 179, 'degree_node1': 181, 'island_area_mean': np.float64(2917913.6339270673), 'island_area_median': np.float64(437092.9988254184), 'island_area_std': np.float64(12039070.78225078), 'island_length_mean': np.float64(5603.703436802752), 'island_length_median': np.float64(3317.207504454762), 'island_length_std': np.float64(7414.772571346336), 'n_islands': 204, 'width_mean': np.float64(1085.8477190959304), 'width_median': np.float64(1034.0424345997312), 'width_std': np.float64(326.5807450961444), 'centerline_length': np.float64(1460209.3834013743), 'sinuosity': np.float64(1.8682284302558785)}

In [64]:
fig, ax = river.plot_overview()
df, curv, s, loc_zero_curv, xsmooth, ysmooth = river.analyze_wavelength_and_width(ax=ax, 
                        delta_s=30.0, smoothing_factor=2*1e8, min_sinuosity=1.1, dx=30)
df.head()

100%|██████████| 204/204 [00:00<00:00, 5543.17it/s]
100%|██████████| 611/611 [00:00<00:00, 4364.48it/s]

,wavelengths (m),sinuosities,mean widths (m),std. dev. of widths (m),along-channel distance (km)
0,12432.419116,1.129290,1115.812539,190.283303,3.527671
1,16352.165701,1.374111,1240.672805,240.144682,50.727841
2,10929.126084,1.221479,973.396952,126.017387,59.641083
3,13507.781866,2.486553,1331.617161,257.702123,80.660382
4,11535.870343,3.752594,1113.627490,216.239425,99.891490

## Adelaide River, Australia

Water mask was generated from Planet Labs data.

Link to data file: https://utexas.box.com/s/g5mgrpw3pir8lwfnlx7nnexggg7o59an

In [65]:
river = rb.River(
    dirname = "data/Adelaide/",
    fname = "ndwi_mosaic.tif",
    start_x = 753443.4,
    start_y = 8598434.2,
    end_x = 743089.7,
    end_y = 8648110.2,
    file_type='water_index'
)

river.map_river_banks(
    ch_belt_smooth_factor=1e8,
    ch_belt_half_width=2000,
    mndwi_threshold=0.5,
    remove_smaller_components=False,
    small_hole_threshold=64,
    solidity_filter=False,
    plot_D_primal=True,
    flip_outlier_edges=False,
    check_edges=False
)

Processing river: ndwi_mosaic.tif
Start point: (753443.4, 8598434.2)
End point: (743089.7, 8648110.2)
Phase 1: Initial setup and skeletonization
running skeletonization
Phase 2: Finding main path with fallbacks
Phase 3: Processing graph and extending edges

100%|██████████| 62/62 [00:00<00:00, 246.88it/s]

Phase 4: Extracting and smoothing main path
Phase 5: Polygonizing centerline network

100%|██████████| 80/80 [00:00<00:00, 22441.43it/s]

Phase 6: Creating channel belt and boundaries
Phase 7: Create UTM geodataframe

0it [00:00, ?it/s]

Phase 8: Create primal graph

2it [00:00,  8.88it/s]

start and end nodes in G_primal:
1 0
Phase 9: Create rook graph

100%|██████████| 29389/29389 [00:06<00:00, 4539.15it/s]
100%|██████████| 30048/30048 [00:06<00:00, 4716.12it/s]
0it [00:00, ?it/s]

Phase 10: Set half channel widths

100%|██████████| 2/2 [00:12<00:00,  6.48s/it]

Phase 11: Create directed graph

100%|██████████| 1/1 [00:00<00:00, 10.99it/s]

Phase 12: Get bank coordinates for main channel

100%|██████████| 28514/28514 [00:06<00:00, 4393.53it/s]
100%|██████████| 28512/28512 [00:06<00:00, 4319.63it/s]
0it [00:00, ?it/s]
100%|██████████| 1/1 [00:00<00:00,  9.06it/s]

✓ Successfully processed ndwi_mosaic.tif
  - Directed graph: 2 nodes, 1 edges
  - Rook graph: 2 polygons
  - Primal graph: 2 nodes

True

In [66]:
river.summary()

=== River Summary: ndwi_mosaic.tif ===
Processed: True
Successful: True
Start point: (753443.4, 8598434.2)
End point: (743089.7, 8648110.2)
Directed graph: 2 nodes, 1 edges
Rook graph: 2 polygons
Primal graph: 2 nodes
MNDWI shape: (17013, 7701)
Main path: 1 edges
Channel width: 246.7 ± 215.0 m
Channel length: 97553.2 m
===================================

### Plot width data for main channel

In [67]:
s, w = river.get_channel_widths()
plt.figure(figsize=(12, 4))
plt.plot(s, w) 
plt.xlabel('along-channel distance (m)')
plt.ylabel('channel width (m)');

### Plot meander wavelength and channel width data

In [68]:
fig, ax = river.plot_overview()
df, curv, s, loc_zero_curv, xsmooth, ysmooth = river.analyze_wavelength_and_width(ax=ax, 
                        delta_s=5.0, smoothing_factor=1e6, min_sinuosity=1.1, dx=3)
df.head()

0it [00:00, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 59.53it/s]

,wavelengths (m),sinuosities,mean widths (m),std. dev. of widths (m),along-channel distance (km)
0,2048.653134,1.253083,118.022035,5.146227,3.211620
1,1839.380726,2.217626,107.060118,5.776349,6.031768
2,3856.776709,1.403601,103.964590,5.518809,8.405024
3,1615.337144,1.187462,114.563243,6.692378,11.904294
4,3170.457006,1.332776,107.543406,6.819417,13.437731

## Lena Delta, Russia


Link to data file: https://utexas.box.com/s/4b87y3og9o40zti0cytye0ppecepncy8

In [56]:
# it takes about 45 minutes to run this!

river = rb.River(
    dirname = "data/Lena/",
    fname = 'lena_1_mndwi_clipped.tif',
    start_x = 437535.424,
    start_y = 7970396.089,
    end_x = 522971.474,
    end_y = 8092767.374,
    file_type='water_index'
)

river.map_river_banks(
    ch_belt_smooth_factor=1e8,
    ch_belt_half_width=100000,
    radius = 1000,
    remove_smaller_components=True,
    small_hole_threshold=64,
    solidity_filter=False,
    plot_D_primal=True,
    flip_outlier_edges=True,
    mndwi_threshold=0.0,
    check_edges=False,
    filter_contours=True
)

Processing river: lena_1_mndwi_clipped.tif
Start point: (437535.424, 7970396.089)
End point: (522971.474, 8092767.374)
Phase 1: Initial setup and skeletonization
running skeletonization
Phase 2: Finding main path with fallbacks
Phase 3: Processing graph and extending edges

100%|██████████| 185/185 [01:49<00:00,  1.70it/s]

Phase 4: Extracting and smoothing main path
Phase 5: Polygonizing centerline network

100%|██████████| 7052/7052 [04:37<00:00, 25.39it/s]

Phase 6: Creating channel belt and boundaries
Phase 7: Create UTM geodataframe

100%|██████████| 1210/1210 [00:00<00:00, 3642.59it/s]

Phase 8: Create primal graph

1212it [04:30,  4.49it/s]

start and end nodes in G_primal:
1 108
Phase 9: Create rook graph

100%|██████████| 12211/12211 [00:03<00:00, 3346.50it/s]
100%|██████████| 12821/12821 [00:08<00:00, 1523.01it/s]
100%|██████████| 1210/1210 [04:55<00:00,  4.09it/s]

Phase 10: Set half channel widths

100%|██████████| 1212/1212 [25:12<00:00,  1.25s/it]

Phase 11: Create directed graph
12206 7
10933 1890

100%|██████████| 3607/3607 [00:45<00:00, 80.12it/s]

Phase 12: Get bank coordinates for main channel

100%|██████████| 5321/5321 [00:02<00:00, 2090.88it/s]
100%|██████████| 5317/5317 [00:02<00:00, 2074.91it/s]
100%|██████████| 1210/1210 [00:00<00:00, 5942.91it/s]
100%|██████████| 3632/3632 [00:01<00:00, 1971.73it/s]

✓ Successfully processed lena_1_mndwi_clipped.tif
  - Directed graph: 2379 nodes, 3632 edges
  - Rook graph: 1212 polygons
  - Primal graph: 2379 nodes

True

In [57]:
river.summary()

=== River Summary: lena_1_mndwi_clipped.tif ===
Processed: True
Successful: True
Start point: (437535.4, 7970396.1)
End point: (522971.5, 8092767.4)
Directed graph: 2379 nodes, 3632 edges
Rook graph: 1212 polygons
Primal graph: 2379 nodes
MNDWI shape: (6569, 4600)
Main path: 58 edges
Channel width: 3976.2 ± 2233.4 m
Channel length: 190436.4 m
============================================

#### Create polyline that is used to define the coastline and channel termini; use it to get channel mouth polygon

In [58]:
from shapely.geometry import Polygon
# these points can be obtained by using 'ginput':
points = [(494904.8, 7970881.4),
 (502959.4, 7975311.4),
 (502355.3, 7987192.0),
 (502153.9, 7991017.9),
 (504368.9, 7991017.9),
 (509000.3, 7983970.1),
 (515444.0, 7984574.2),
 (520880.9, 7997663.0),
 (523297.2, 8022229.5),
 (523095.9, 8045185.1),
 (522693.2, 8076396.7),
 (521686.3, 8101366.0),
 (513229.0, 8119488.9),
 (501549.8, 8135195.3),
 (488461.1, 8148888.2),
 (471949.1, 8159761.9),
 (453423.6, 8163587.8),
 (438925.3, 8163185.1)]

x_utm, y_utm, ch_map = rb.get_channel_mouth_polygon(river._mndwi, river.dataset, points)
fig, ax = river.plot_mndwi()
ax.plot(x_utm, y_utm, 'g', linewidth=3)
ch_poly = rb.create_channel_nw_polygon(river._G_rook, buffer=10, 
                ch_mouth_poly=Polygon(np.vstack((x_utm, y_utm)).T), 
                dataset=river.dataset)

100%|██████████| 665/665 [00:01<00:00, 375.97it/s]

#### Recreate directed graph

In [59]:
D_primal, sources, sinks = rb.create_directed_multigraph(river._G_primal,
        river._G_rook, river._xs, river._ys, 1, 108, flip_outlier_edges=True, check_edges=False,
        x_utm=x_utm, y_utm=y_utm)
fig, ax = river.plot_mndwi()
rb.plot_graph_w_colors(D_primal, ax)

12206 7
10933 1890

100%|██████████| 3607/3607 [00:29<00:00, 121.19it/s]

Removed 141 nodes inside the polygon
Added 136 new nodes at edge intersections
Created 136 new boundary nodes
Total sink nodes in truncated graph: 140
Total source nodes in truncated graph: 17

100%|██████████| 3470/3470 [00:01<00:00, 2000.70it/s]

In [196]:
import pickle

with open('/Users/zoltan/Documents/Rivabar/rivabar/data/Lena/lena_delta_g_rook.pkl', 'rb') as f:
    G_rook_lena = pickle.load(f)

with open('/Users/zoltan/Documents/Rivabar/rivabar/data/Lena/lena_delta_d_primal.pkl', 'rb') as f:
    D_primal_lena = pickle.load(f)

print(f"G_rook: {G_rook_lena.number_of_nodes()} nodes, {G_rook_lena.number_of_edges()} edges")
print(f"D_primal: {D_primal_lena.number_of_nodes()} nodes, {D_primal_lena.number_of_edges()} edges")

G_rook: 1212 nodes, 3461 edges
D_primal: 2374 nodes, 3470 edges

In [197]:
island_areas = []
channel_areas = []
total_areas = []
degrees = []
lengths = []


for node in G_rook_lena:
    poly1 = G_rook_lena.nodes()[node]['bank_polygon']
    poly2 = G_rook_lena.nodes()[node]['cl_polygon']
    
    if poly1.area > 0 and poly2.area > poly1.area:
        island_areas.append(poly1.area)
        channel_areas.append(poly2.area - poly1.area)
        total_areas.append(poly2.area)
        degrees.append(G_rook_lena.degree(node))
        lengths.append(poly1.length)

In [ ]:
plt.figure()
plt.hist(degrees, bins=bins, density=True, alpha=0.7);

(array([0.10107705, 0.16818558, 0.1946976 , 0.13753107, 0.12510356,
        0.08864954, 0.04142502, 0.04971002, 0.01988401, 0.02319801,
        0.01491301, 0.009942  , 0.0091135 , 0.004971  , 0.0041425 ,
        0.0008285 , 0.001657  , 0.        , 0.        , 0.001657  ,
        0.0024855 , 0.        , 0.        , 0.0008285 ]),
 array([ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5,
        12.5, 13.5, 14.5, 15.5, 16.5, 17.5, 18.5, 19.5, 20.5, 21.5, 22.5,
        23.5, 24.5, 25.5]),
 <BarContainer object of 24 artists>)

## Javari

Example for tributary detection

In [ ]:
river = rb.River(
    dirname = "/Users/zoltan/Documents/Rivabar/mndwi_data/Javari_1/",
    fname = "mndwi_LC08_005063_20170715.tif",
    start_x = 91568.3,
    start_y = -560299.4,
    end_x = 309310.2,
    end_y = -462211.5,
    file_type='water_index'
)

river.map_river_banks(min_tributary_length=100)  # only keep branches >= 20 nodes

Processing river: mndwi_LC08_005063_20170715.tif
Start point: (91568.3, -560299.4)
End point: (309310.2, -462211.5)
Phase 1: Initial setup and skeletonization
running skeletonization
Phase 2: Finding main path with fallbacks
Phase 3: Processing graph and extending edges

100%|██████████| 19/19 [00:00<00:00, 1966.29it/s]

Phase 4: Extracting and smoothing main path
Phase 5: Polygonizing centerline network

100%|██████████| 19/19 [00:00<00:00, 8950.11it/s]

Phase 6: Creating channel belt and boundaries
Phase 7: Create UTM geodataframe

0it [00:00, ?it/s]

Phase 8: Create primal graph

2it [00:00, 16.85it/s]

start and end nodes in G_primal:
0 1
Phase 9: Create rook graph

100%|██████████| 16135/16135 [00:00<00:00, 41790.77it/s]
100%|██████████| 16244/16244 [00:00<00:00, 40320.80it/s]
0it [00:00, ?it/s]

Phase 10: Set half channel widths

100%|██████████| 2/2 [00:04<00:00,  2.38s/it]

Phase 11: Create directed graph

100%|██████████| 1/1 [00:00<00:00, 19.64it/s]

Phase 12: Get bank coordinates for main channel

100%|██████████| 15735/15735 [00:00<00:00, 42091.53it/s]
100%|██████████| 15735/15735 [00:00<00:00, 38487.60it/s]

✓ Successfully processed mndwi_LC08_005063_20170715.tif
  - Directed graph: 2 nodes, 1 edges
  - Rook graph: 2 polygons
  - Primal graph: 2 nodes

True

In [86]:
fig, ax = river.plot_overview()

0it [00:00, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 101.69it/s]

In [87]:
for trib in river.tributary_confluences:                                                                                                                                                   
    utm_x, utm_y = trib['confluence_utm_coords']                                                                                                                                           
    length = trib['branch_length_pixels']                                                                                                                                                  
    print(f"Tributary at ({utm_x:.1f}, {utm_y:.1f}), length: {length:.0f} pixels")

Tributary at (233520.0, -491730.0), length: 8742 pixels
Tributary at (190350.0, -496350.0), length: 2600 pixels
Tributary at (159450.0, -515910.0), length: 134 pixels

In [88]:
# Plot the main channel belt (existing functionality)                                                                                                                                      
fig, ax = rb.plot_im_and_lines(
    river.mndwi,
    river.bounds['left'], river.bounds['right'],
    river.bounds['lower'], river.bounds['upper'],
    river.bankline_graph, river.centerline_graph, river.directed_graph,
    smoothing=False, plot_lines=False
)
rb.plot_graph_w_colors(river.directed_graph, ax)

# Overlay tributaries
for trib in river.tributary_confluences:
    # Plot the tributary branch
    coords = trib['branch_utm_coords']
    ax.plot(coords[:, 0], coords[:, 1], 'r-', linewidth=2)
    # Mark the confluence point
    cx, cy = trib['confluence_utm_coords']
    ax.plot(cx, cy, 'ro', markersize=8)

0it [00:00, ?it/s]
100%|██████████| 1/1 [00:00<00:00, 16.33it/s]

In [84]:
len(river.tributary_confluences)

1